version: '3'
services:
  web:
    image: node:6.11
    ports:
    - "3000:3000"
    working_dir: /code
    environment:
      - DEBUG=powerup-blog:*
    volumes:
    - ./:/code
    - logvolume01:/var/log
    command: /bin/bash -c " npm install && npm start"
volumes:
  logvolume01: {}